---
title: "mtb_in_LTBI_large"
author: "Sashank Batchu"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
devtools::install_github("BIGslu/kimma")
BiocManager::install("edgeR")

install.packages("gtsummary")
library(gtsummary)
library(dplyr)
library(limma)
library(tidyverse)
library(BIGverse)
library(DiagrammeR)
library(kimma)
library(edgeR)
library(patchwork)
library(devtools)
library(edgeR)
library(BIGpicture)

#load data 
load("~/Documents/GitHub/kimma_MS_public/data/RSTR_RNAseq_data_combined_uniqueFULLID_weights.RData") #full data 
load("~/Documents/GitHub/kimma_MS_public/data/RSTR_RNAseq_kinship.RData")
load("~/Documents/GitHub/kimma_MS_public/data/RSTR_kimma_voom.RData") # 92 indiv data (ones with kindship)

#subset voom for LTBI vs RSTR
dat_LTBI_vs_RSTR <- datV

dat_LTBI_vs_RSTR$targets <- datV$targets %>% 
  filter(condition == "MEDIA")

dat_LTBI_vs_RSTR$E <- as.data.frame(dat_LTBI_vs_RSTR$E) %>% 
  rownames_to_column("geneName") %>% 
  select(geneName, all_of(dat_LTBI_vs_RSTR$targets$libID)) %>% 
  column_to_rownames("geneName")

LTBI_vs_RSTR_vector <- datV$targets$libID %in% dat_LTBI_vs_RSTR$targets$libID
dat_LTBI_vs_RSTR$weights <- dat_LTBI_vs_RSTR$weights[, LTBI_vs_RSTR_vector]

#subset voom for media vs tb
dat_media_vs_tb <- datV

dat_media_vs_tb$targets <- datV$targets %>% 
  filter(Sample_Group == "LTBI")

dat_media_vs_tb$E <- as.data.frame(dat_media_vs_tb$E) %>% 
  rownames_to_column("geneName") %>% 
  select(geneName, all_of(dat_media_vs_tb$targets$libID)) %>% 
  column_to_rownames("geneName")

media_vs_tb_vector <- datV$targets$libID %in% dat_media_vs_tb$targets$libID

dat_media_vs_tb$weights <- dat_media_vs_tb$weights[, media_vs_tb_vector]

```

``` {r LTBI vs RSTR sample_group (limma and kimma)}
#### No weights ####
#### Limma
dat_LTBI_vs_RSTR$weights = NULL
mm_LTBI_vs_RSTR_limma <- model.matrix(~ Sample_Group, data= dat_LTBI_vs_RSTR$targets)

fit <- lmFit(object = dat_LTBI_vs_RSTR,
             design = mm_LTBI_vs_RSTR_limma, 
             weights = NULL)
efit <- eBayes(fit)
results_limma_LTBI_vs_RSTR <- kimma::extract_lmFit(design=mm_LTBI_vs_RSTR_limma, fit=efit)

save(efit, results_limma_LTBI_vs_RSTR, file= "Sample_Group_limma.RData")

#### Kimma 
fit <- kmFit(dat = dat_LTBI_vs_RSTR,
             model = "~ Sample_Group",
             run.lm = TRUE, 
             patientID = "ptID", 
             use.weights = FALSE)
results_kimma_LTBI_vs_RSTR <- fit$lm
summarise_kmFit(results_kimma_LTBI_vs_RSTR)
save(fit, results_kimma_LTBI_vs_RSTR, file = "Sample_Group_kimma.RData")


#### With Weights####
#### Limma
#Add weights 
dat_LTBI_vs_RSTR$weights <- datV$weights[, LTBI_vs_RSTR_vector]

mm_LTBI_vs_RSTR_limma <- model.matrix(~ Sample_Group, data=dat_LTBI_vs_RSTR$targets)

fit <- lmFit(object = dat_LTBI_vs_RSTR, 
             design = mm_LTBI_vs_RSTR_limma,
             weights =  dat_LTBI_vs_RSTR$weights)
efit <- eBayes(fit)
results_limma_LTBI_vs_RSTR_weights <- kimma::extract_lmFit(design=mm_LTBI_vs_RSTR_limma, fit=efit)

save(efit, results_limma_LTBI_vs_RSTR_weights, file = "Sample_Group_limma_weights.RData")

#### Kimma 
fit <- kmFit(dat = dat_LTBI_vs_RSTR,
             model = "~ Sample_Group",
             run.lm = TRUE, 
             patientID = "ptID", 
             use.weights = TRUE)
results_kimma_LTBI_vs_RSTR_weights <- fit$lm
summarise_kmFit(results_kimma_LTBI_vs_RSTR_weights)
save(fit, results_kimma_LTBI_vs_RSTR_weights, file= "Sample_Group_kimma_weights.RData")

#### Kinship (No weights) ####
dat_LTBI_vs_RSTR$weights = NULL

fit <- kmFit(dat = dat_LTBI_vs_RSTR, 
             model = "~Sample_Group + (1|ptID)", 
             patientID = "ptID", 
             kin = kin.matrix, 
             run.lmekin = TRUE)
results_kimma_LTBI_vs_RSTR_kinship <- fit$lmekin
save(fit, results_kimma_LTBI_vs_RSTR_kinship, file = "Sample_Group_kimma_kinship.RData")

#### Kinship (Weights) ####
fit <- kmFit(dat = dat_LTBI_vs_RSTR,
             model = "~ Sample_Group + (1|ptID)",
             patientID = "ptID",
             kin = kin.matrix, 
             run.lmekin = TRUE, 
             use.weights = TRUE)
results_kimma_LTBI_vs_RSTR_kinship_weights <- fit$lmekin
save(fit, results_kimma_LTBI_vs_RSTR_kinship_weights, file = "Sample_Group_kimma_kinship_weights.RData")

#### Bring data results back into environment for KIMMA
test <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_kimma.RData") #kimma no weights/kinship
results_kimma_LTBI_vs_RSTR <- test$results_kimma_LTBI_vs_RSTR

test <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_kimma_weights.RData") # kimma with weights no kinship
results_kimma_LTBI_vs_RSTR_weights <- test$results_kimma_LTBI_vs_RSTR_weights

test <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_kimma_kinship.RData") #kimma kinship no weights
results_kimma_LTBI_vs_RSTR_kinship <- test$results_kimma_LTBI_vs_RSTR_kinship

test <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_kimma_kinship_weights.RData")
results_kimma_LTBI_vs_RSTR_kinship_weights <- test$results_kimma_LTBI_vs_RSTR_kinship_weights
```

```{r DEG - LTBI vs RSTR}
#### LIMMA ####
Sample_Group_limma <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_limma.RData")
media.efit.noW <- Sample_Group_limma$efit
media.results.limma.noW <- Sample_Group_limma$results_limma_LTBI_vs_RSTR

Sample_Group_limma_weights <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_limma_weights.RData")
media.efit.W <- Sample_Group_limma_weights$efit
media.results.limma.W <- Sample_Group_limma_weights$results_limma_LTBI_vs_RSTR_weights

## Venn 
venn.ls <- list()
venn.ls[["noW"]] <- media.results.limma.noW %>% 
  filter(variable == "Sample_GroupRSTR" & adj.P.Val < 0.2) %>% 
  distinct(symbol) %>% unlist()
venn.ls[["W"]] <- media.results.limma.W %>% 
  filter(variable == "Sample_GroupRSTR" & adj.P.Val < 0.2) %>% 
  distinct(symbol) %>% unlist()

#### KIMMA ####
Sample_Group_kimma <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_kimma.RData")
media.efit.k.noW <- Sample_Group_kimma$fit
media.results.kimma.noW <- Sample_Group_kimma$results_kimma_LTBI_vs_RSTR

Sample_Group_kimma_weights <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_kimma_weights.RData")
media.efit.k.W <- Sample_Group_kimma_weights$fit
media.results.kimma.W <- Sample_Group_kimma_weights$results_kimma_LTBI_vs_RSTR_weights

Sample_Group_kimma_kinship <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_kimma_kinship.RData")
results_kimma_LTBI_vs_RSTR_kinship <- Sample_Group_kimma_kinship$results_kimma_LTBI_vs_RSTR_kinship

Sample_Group_kimma_kinship_weights <- attach("~/Documents/GitHub/kimma_MS_public/results/model_fit/Sample_Group_kimma_kinship_weights.RData")

results_kimma_LTBI_vs_RSTR_kinship_weights <- Sample_Group_kimma_kinship_weights$results_kimma_LTBI_vs_RSTR_kinship_weights

venn.ls2 <- list()
venn.ls2[["noW"]] <- media.results.kimma.noW %>% 
  filter(variable == "Sample_GroupRSTR" & FDR < 0.2) %>% 
  distinct(gene) %>% unlist()
venn.ls2[["W"]] <- media.results.kimma.W %>% 
  filter(variable == "Sample_GroupRSTR" & FDR < 0.2) %>% 
  distinct(gene) %>% unlist()
venn.ls2[["Kin"]] <- results_kimma_LTBI_vs_RSTR_kinship %>% 
  filter(variable == "Sample_GroupRSTR" & FDR < 0.2) %>% 
  distinct(gene) %>% unlist()
venn.ls2[["KinW"]] <- results_kimma_LTBI_vs_RSTR_kinship_weights %>% 
  filter(variable == "Sample_GroupRSTR" & FDR < 0.2) %>% 
  distinct(gene) %>% unlist()

#table to summarize results
sig_genes_table <- as.data.frame(c("TSHZ2", "3.282051e-02", "kimma_W_noKin, kimma_Kin_noW, kimma_Kin_W"), ncol = 3, byrow = TRUE)
rownames(sig_genes_table) <- c("Symbol", "FDR", "Model")
colnames(sig_genes_table) <- "Sig_Gene"
  
all_models_df <- results_limma_LTBI_vs_RSTR %>%
      filter(variable == "Sample_GroupRSTR") %>% 
      select(symbol, P.Value, adj.P.Val) %>% 
      rename("Limma_noW_P.Value" = "P.Value", "Limma_noW_FDR" = "adj.P.Val") %>% 
  full_join(filter(results_limma_LTBI_vs_RSTR_weights, variable == "Sample_GroupRSTR"), by = "symbol") %>% 
      select(symbol, Limma_noW_P.Value, Limma_noW_FDR, P.Value, adj.P.Val) %>% 
      rename("Limma_W_P.Value" = "P.Value", "Limma_W_FDR" = "adj.P.Val") %>% 
  full_join(filter(results_kimma_LTBI_vs_RSTR, variable == "Sample_GroupRSTR"), by = c("symbol" = "gene")) %>% 
      select(symbol, Limma_noW_P.Value, Limma_noW_FDR, Limma_W_P.Value, Limma_W_FDR, pval, FDR) %>% 
      rename("Kimma_noW_noKin_P.Value" = "pval", "Kimma_noW_noKin_FDR" = "FDR") %>%  
  full_join(filter(results_kimma_LTBI_vs_RSTR_weights, variable == "Sample_GroupRSTR"), by = c("symbol" = "gene")) %>%  
      select(symbol, Limma_noW_P.Value, Limma_noW_FDR, Limma_W_P.Value, Limma_W_FDR, Kimma_noW_noKin_P.Value, Kimma_noW_noKin_FDR, pval, FDR) %>% 
      rename("Kimma_W_noKin_P.Value" = "pval", "Kimma_W_noKin_FDR" = "FDR") %>% 
  full_join(filter(results_kimma_LTBI_vs_RSTR_kinship, variable == "Sample_GroupRSTR"), by = c("symbol" = "gene")) %>% 
      select(symbol, Limma_noW_P.Value, Limma_noW_FDR, Limma_W_P.Value, Limma_W_FDR, Kimma_noW_noKin_P.Value, Kimma_noW_noKin_FDR, Kimma_W_noKin_P.Value, Kimma_W_noKin_FDR, pval, FDR) %>%  
      rename("Kimma_noW_Kin_P.Value" = "pval", "Kimma_noW_Kin_FDR" = "FDR") %>% 
  full_join(filter(results_kimma_LTBI_vs_RSTR_kinship_weights, variable == "Sample_GroupRSTR"), by = c("symbol" = "gene")) %>% 
      select(symbol, Limma_noW_P.Value, Limma_noW_FDR, Limma_W_P.Value, Limma_W_FDR, Kimma_noW_noKin_P.Value, Kimma_noW_noKin_FDR, Kimma_W_noKin_P.Value, Kimma_W_noKin_FDR, Kimma_noW_Kin_P.Value, Kimma_noW_Kin_FDR, pval, FDR) %>% 
      rename("Kimma_W_Kin_P.Value" = "pval", "Kimma_W_Kin_FDR" = "FDR") 
```


```{r media vs tb condition (limma and kimma)}
#### No weights ####
#### Limma
mm_media_vs_tb_limma <- model.matrix(~ condition, data= dat_media_vs_tb$targets)

dat_media_vs_tb$weights <- NULL

fit <- lmFit(object=dat_media_vs_tb, design=mm_media_vs_tb_limma)
efit <- eBayes(fit)
results_limma_media_vs_tb <- kimma::extract_lmFit(design=mm_media_vs_tb_limma, fit=efit)

save(efit, results_limma_media_vs_tb, file= "condition_limma.RData")

#### Kimma 
fit <- kmFit(dat = dat_media_vs_tb, model = "~ condition" , run.lm = TRUE, patientID = "ptID")
results_kimma_media_vs_tb <- fit$lm
summarise_kmFit(results_kimma_media_vs_tb)
save(fit, results_kimma_media_vs_tb, file= "condition_kimma.RData")

#### With Weights####
#### Limma
#Add weights 
dat_media_vs_tb$weights <- datV$weights[, media_vs_tb_vector]

mm_media_vs_tb_limma <- model.matrix(~ condition, data=dat_media_vs_tb$targets)

fit <- lmFit(object= dat_media_vs_tb, design= mm_media_vs_tb_limma)
efit <- eBayes(fit)
results_limma_media_vs_tb_weights <- kimma::extract_lmFit(design=mm_media_vs_tb_limma, fit=efit)

save(efit, results_limma_media_vs_tb_weights, file = "condition_limma_weights.RData")

#### Kimma 
dat_media_vs_tb$weights <- datV$weights[, media_vs_tb_vector]

fit <- kmFit(dat = dat_media_vs_tb, model = "~ condition" , run.lm = TRUE, patientID = "ptID")
results_kimma_media_vs_tb_weights <- fit$lm
summarise_kmFit(results_kimma_media_vs_tb_weights)

save(fit, results_kimma_media_vs_tb_weights, file= "condition_kimma_weights.RData")
```

```{r sample}

#### edgeR ####
#subset DGElist
dat_LTBI_edgeR <- dat.combined

dat_LTBI_edgeR$samples <- dat_LTBI_edgeR$samples %>% 
  filter(Sample_Group == "LTBI") %>% 
  mutate(., group = case_when(condition == "TB" ~ 2, condition == "MEDIA" ~ 1))

dat_LTBI_edgeR$counts <- as.data.frame(dat_LTBI_edgeR$counts) %>% 
  rownames_to_column("geneName") %>% 
  select(geneName, all_of(dat_LTBI_edgeR$samples$libID)) %>% 
  column_to_rownames("geneName")


#prep
keep <- filterByExpr(dat_LTBI_edgeR)
dat_LTBI_edgeR <- dat_LTBI_edgeR[keep, , keep.lib.sizes=FALSE]
design <- model.matrix(~ condition, data=dat_LTBI_edgeR$samples)
dat_LTBI_edgeR <- estimateCommonDisp(dat_LTBI_edgeR)



#run ExactTest
et <- exactTest(dat_LTBI_edgeR)
topTags(et)




logical.vector <- dat.combined.voom$targets$libID %in% dat.subset$targets$libID
logical.vector

dat.subset$weights <- dat.subset$weights[,logical.vector]

dim(dat.subset$E)
dim(dat.subset$targets)
dim(dat.subset$weights)

#limma
#Create model "design"
mm_limma <- model.matrix(~ condition, data=dat.subset$targets)
mm_limma

#Remove weights if not using
dat.subset$weights <- NULL

fit <- lmFit(object=dat.subset, design=mm_limma)
efit <- eBayes(fit)
results <- kimma::extract_lmFit(design=mm_limma, fit=efit)

```